---
- shell: /bin/bash -c 'echo "  Configuring services..." > {{ fifo}}'

- name: Stop kernel NFS
  service: name=nfs state=stopped

- name: Disable kernel NFS
  service: name=nfs enabled=no

- name: Stop network manager service
  service: name=NetworkManager state=stopped
  ignore_errors: yes

- name: Disable network manager service
  service: name=NetworkManager enabled=no
  ignore_errors: yes

- name: Start network service
  service: name=network state=started

- name: Enable network service
  service: name=network enabled=yes

- name: Start pcsd service
  service: name=pcsd state=started

- name: Enable pcsd service
  service: name=pcsd enabled=yes

- name: Define service port
  lineinfile:
    dest: /etc/sysconfig/nfs
    regexp: '^#STATD_PORT=.*'
    line: 'STATD_PORT=662'

- name: Restart nfs-config service
  service:
    name: nfs-config
    state: restarted
  ignore_errors: yes

- name: Restart rpc-statd service
  service:
    name: rpc-statd
    state: restarted
  ignore_errors: yes

- shell: /bin/bash -c 'echo "  Enabling shared storage volume..." > {{ fifo}}'

- name: Enable Gluster shared storage volume
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  volume_set:
    action: set
    volume: all
    key: cluster.enable-shared-storage
    value: enable
  ignore_errors: true

- shell: /bin/bash -c 'echo "  Authenticating HA cluster..." > {{ fifo}}'

- name: Generate hacluster password
  run_once: true
  no_log: true
  set_fact:
    hacluster_password: "{{ lookup('password', '/dev/null') }}"

- name: Create a user hacluster in all the cluster nodes if not already present
  no_log: true
  user:
    name: hacluster
    password: "{{ hacluster_password | password_hash('sha512') }}"

- name: Build host list for pcs cluster auth
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  set_fact:
    pcs_hosts: "{{ ha_cluster_nodes.split(',') | join(' ') }}"

- name: Pcs cluster authenticate the hacluster users in all the nodes
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  no_log: true
  shell: "echo '{{ hacluster_password }}' | pcs cluster auth -u hacluster {{ pcs_hosts }}"
  register: result

- name: Pause for a few seconds after pcs auth
  pause: seconds=3

- shell: /bin/bash -c 'echo "  Generating and distributing root SSH keys..." > {{ fifo}}'

- name: Generate ssh key in one of the nodes in HA cluster
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  shell: echo -e  'y\n'|ssh-keygen -q -t rsa -N "" -f /var/lib/glusterd/nfs/secret.pem

- name: Copy the public key to remote nodes
  copy:
    src: "/var/lib/glusterd/nfs/secret.pem.pub"
    dest: "/var/lib/glusterd/nfs/secret.pem.pub"
    mode: 0644

- name: Copy the private key to remote node
  copy:
    src: "/var/lib/glusterd/nfs/secret.pem"
    dest: "/var/lib/glusterd/nfs/secret.pem"
    mode: 0600

- name: Create /root/.ssh directory
  file:
    path: "/root/.ssh"
    state: directory

- name: Deploy the pubkey ~/root/.ssh/authorized_keys on all nodes
  shell: 'cat /var/lib/glusterd/nfs/secret.pem.pub >> ~/.ssh/authorized_keys'

- shell: /bin/bash -c 'echo "  Populating NFS-Ganesha configuration..." > {{ fifo}}'

- name: Create configuration directory for nfs-ganesha
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  file:
    path: "{{ ha_base_dir }}"
    state: directory

- name: Copy ganesha.conf to config directory on shared volume
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  shell: 'cp -rf /etc/ganesha/* "{{ ha_base_dir }}"'

- name: Create VIP entries variable for ganesha-ha.conf
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  set_fact:
    vip_entries: |
      {{ vip_entries | default() }}
      {{ item }}
  with_items: "{{ vip_list }}"

- name: Creating ganesha-ha.conf file
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  template:
    src: g1-ganesha-ha.j2
    dest: "{{ ha_base_dir }}/ganesha-ha.conf"

- shell: /bin/bash -c 'echo "  Enabling NFS-Ganesha services..." > {{ fifo}}'

- name: Enable nfs-ganesha
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  shell: gluster nfs-ganesha enable --mode=script
  register: result
  failed_when:
    - "'is already enabled' not in result.stderr"
    - "'success' not in result.stderr"
    - "'success' not in result.stdout"
  ignore_errors: yes

- name: Pause for 30 seconds (takes a while to enable NFS Ganesha)
  pause: seconds=30

- name: Check NFS Ganesha status
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  shell: /usr/libexec/ganesha/ganesha-ha.sh --status "{{ ha_base_dir}}" | \
         grep 'Cluster HA Status'
  register: result
  ignore_errors: yes

- name: Report NFS Ganesha status
  debug: msg={{ result.stdout }} verbosity=0
  when: result.stderr == ""

- name: Report NFS Ganesha status (If any errors)
  debug: msg={{ result.stderr }} verbosity=0
  when: result.stderr != ""

- name: Enable pacemaker service
  service: name=pacemaker enabled=yes

- name: Export default volume with NFS-Ganesha
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  volume_set:
    action: set
    volume: "{{ default_volname }}"
    key: "ganesha.enable"
    value: "on"
